#!/usr/bin/env node
/**
 * Independent Version Management Script
 *
 * Frontend and backend versions are managed independently.
 * Each component tracks its own MAJOR.MINOR version in separate VERSION files.
 */

const fs = require('fs');
const path = require('path');

// Version file paths
const frontendVersionPath = path.join(__dirname, '..', 'frontend', 'VERSION');
const backendVersionPath = path.join(__dirname, '..', 'backend', 'VERSION');
const versionTsPath = path.join(__dirname, '..', 'frontend', 'src', 'version.ts');
const versionPyPath = path.join(__dirname, '..', 'backend', '__init__.py');

function getVersionFromFile(filePath) {
    try {
        return fs.readFileSync(filePath, 'utf8').trim();
    } catch {
        return '1.0';
    }
}

function setVersionInFile(filePath, version) {
    fs.writeFileSync(filePath, version + '\n');
}

function updateFrontendSource(version) {
    const content = `// Frontend version - auto-generated by CI
export const VERSION = '${version}'
`;
    fs.writeFileSync(versionTsPath, content);
}

function updateBackendSource(version) {
    let content = fs.readFileSync(versionPyPath, 'utf8');
    content = content.replace(
        /__version__\s*=\s*['"][^'"]+['"]/,
        `__version__ = '${version}'`
    );
    fs.writeFileSync(versionPyPath, content);
}

function getFrontendVersion() {
    return getVersionFromFile(frontendVersionPath);
}

function getFrontendFullVersion() {
    const majorMinor = getFrontendVersion();
    const build = process.env.BUILD_NUMBER || 'DEV';
    return `${majorMinor}.${build}`;
}

function getBackendVersion() {
    return getVersionFromFile(backendVersionPath);
}

function getBackendFullVersion() {
    const majorMinor = getBackendVersion();
    const build = process.env.BUILD_NUMBER || 'DEV';
    return `${majorMinor}.${build}`;
}

function incrementMinor(majorMinor) {
    const [major, minor = 0] = majorMinor.split('.').map(Number);
    return `${major}.${minor + 1}`;
}

function setComponentMajor(component, major) {
    const majorMinor = `${major}.0`;
    const fullVersion = `${major}.0.0`;

    if (component === 'frontend') {
        setVersionInFile(frontendVersionPath, majorMinor);
        updateFrontendSource(fullVersion);
        console.log(`Set frontend version to ${fullVersion}`);
    } else if (component === 'backend') {
        setVersionInFile(backendVersionPath, majorMinor);
        updateBackendSource(fullVersion);
        console.log(`Set backend version to ${fullVersion}`);
    }
}

function setComponentBuild(component, buildNumber) {
    if (component === 'frontend') {
        const majorMinor = getFrontendVersion();
        const fullVersion = `${majorMinor}.${buildNumber}`;
        updateFrontendSource(fullVersion);
        console.log(`Set frontend build to ${fullVersion}`);
    } else if (component === 'backend') {
        const majorMinor = getBackendVersion();
        const fullVersion = `${majorMinor}.${buildNumber}`;
        updateBackendSource(fullVersion);
        console.log(`Set backend build to ${fullVersion}`);
    }
}

function incrementComponentMinor(component) {
    if (component === 'frontend') {
        const current = getFrontendVersion();
        const next = incrementMinor(current);
        setVersionInFile(frontendVersionPath, next);
        const fullVersion = `${next}.0`;
        updateFrontendSource(fullVersion);
        console.log(`Incremented frontend version to ${fullVersion}`);
    } else if (component === 'backend') {
        const current = getBackendVersion();
        const next = incrementMinor(current);
        setVersionInFile(backendVersionPath, next);
        const fullVersion = `${next}.0`;
        updateBackendSource(fullVersion);
        console.log(`Incremented backend version to ${fullVersion}`);
    }
}

// CLI handling
const component = process.argv[2];
const command = process.argv[3];
const arg = process.argv[4];

if (!component) {
    console.log('Frontend version:', getFrontendFullVersion());
    console.log('Backend version:', getBackendFullVersion());
} else if (component === 'frontend') {
    if (command === 'get') {
        console.log(getFrontendFullVersion());
    } else if (command === 'major') {
        setComponentMajor('frontend', arg);
    } else if (command === 'build') {
        setComponentBuild('frontend', arg);
    } else if (command === 'increment-minor') {
        incrementComponentMinor('frontend');
    } else {
        console.log('Frontend version:', getFrontendFullVersion());
    }
} else if (component === 'backend') {
    if (command === 'get') {
        console.log(getBackendFullVersion());
    } else if (command === 'major') {
        setComponentMajor('backend', arg);
    } else if (command === 'build') {
        setComponentBuild('backend', arg);
    } else if (command === 'increment-minor') {
        incrementComponentMinor('backend');
    } else {
        console.log('Backend version:', getBackendFullVersion());
    }
}
