#!/usr/bin/env node
/**
 * Independent Version Management Script
 *
 * Frontend and backend versions are managed independently.
 * Each component tracks its own MAJOR.MINOR version in separate VERSION files.
 * Build numbers are only applied for release tags, not stored in VERSION files.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Version file paths
const frontendVersionPath = path.join(__dirname, '..', 'frontend', 'VERSION');
const backendVersionPath = path.join(__dirname, '..', 'backend', 'VERSION');
const versionTsPath = path.join(__dirname, '..', 'frontend', 'src', 'version.ts');

function hasGitChanges(directory) {
    /**
     * Check if a directory has changes between current branch and main.
     *
     * @param {string} directory - Directory path relative to repo root (e.g., 'frontend/', 'backend/')
     * @returns {boolean} True if directory has changes compared to main, false otherwise
     */
    try {
        // Check for changes between current branch and main
        // Using main...HEAD to compare (or origin/main if main doesn't exist locally)
        let baseBranch = 'main';
        try {
            execSync('git rev-parse --verify main', { stdio: 'pipe' });
        } catch {
            // Try origin/main if main doesn't exist
            try {
                execSync('git rev-parse --verify origin/main', { stdio: 'pipe' });
                baseBranch = 'origin/main';
            } catch {
                // Try master as fallback
                try {
                    execSync('git rev-parse --verify master', { stdio: 'pipe' });
                    baseBranch = 'master';
                } catch {
                    baseBranch = 'origin/master';
                }
            }
        }

        // git diff --quiet exits with 0 if no changes, 1 if changes exist
        // execSync throws on non-zero exit, so if this line completes, no changes exist
        execSync(`git diff --quiet ${baseBranch}...HEAD -- ${directory}`, { encoding: 'utf8', stdio: 'pipe' });
        return false; // No changes
    } catch (error) {
        if (error.status === 1) {
            return true; // Has changes
        }
        // Git not available or other error - assume changes exist to be safe
        console.warn(`Warning: Could not check git status for ${directory}`);
        return true;
    }
}

function setVersionInFile(filePath, version) {
    // Ensure directory exists
    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(filePath, version + '\n');
}

function updateFrontendSource(version) {
    // Only update version.ts with MAJOR.MINOR (no build number in source)
    const content = `// Frontend version - auto-generated by version script
export const VERSION = '${version}'
`;
    fs.writeFileSync(versionTsPath, content);
}

function getFrontendVersion() {
    try {
        if (fs.existsSync(versionTsPath)) {
            const content = fs.readFileSync(versionTsPath, 'utf8');
            const match = content.match(/VERSION = '(\d+\.\d+)(?:\.\d+)?'/);
            if (match) {
                return match[1];
            }
        }
        return '0.0';
    } catch {
        return '0.0';
    }
}

function getBackendVersion() {
    try {
        if (fs.existsSync(backendVersionPath)) {
            return fs.readFileSync(backendVersionPath, 'utf8').trim();
        }
        return '0.0';
    } catch {
        return '0.0';
    }
}

function getReleaseVersion() {
    /**
     * Get the full release version combining frontend and backend.
     * Format: {FRONTEND_VERSION}-{BACKEND_VERSION}-{BUILD_NUMBER}
     * Example: 0.3-0.7-42
     */
    const frontendVersion = getFrontendVersion();
    const backendVersion = getBackendVersion();
    const build = process.env.BUILD_NUMBER || 'DEV';
    return `${frontendVersion}-${backendVersion}-${build}`;
}

function incrementMinor(majorMinor) {
    const [major, minor = 0] = majorMinor.split('.').map(Number);
    return `${major}.${minor + 1}`;
}

function setComponentMajor(component, major) {
    const majorMinor = `${major}.0`;

    if (component === 'frontend') {
        updateFrontendSource(majorMinor);
        console.log(`Set frontend version to ${majorMinor}`);
    } else if (component === 'backend') {
        setVersionInFile(backendVersionPath, majorMinor);
        console.log(`Set backend version to ${majorMinor}`);
    }
}

function incrementComponentMinor(component) {
    if (component === 'frontend') {
        const current = getFrontendVersion();
        const next = incrementMinor(current);
        updateFrontendSource(next);
        console.log(`Incremented frontend version to ${next}`);
    } else if (component === 'backend') {
        const current = getBackendVersion();
        const next = incrementMinor(current);
        setVersionInFile(backendVersionPath, next);
        console.log(`Incremented backend version to ${next}`);
    }
}

function incrementChangedComponents() {
    /**
     * Automatically increment versions for components with changes compared to main branch.
     * Only increments if there are changes in the component's directory.
     */
    const frontendChanged = hasGitChanges('frontend/');
    const backendChanged = hasGitChanges('backend/');

    if (frontendChanged) {
        console.log('Frontend changes detected (compared to main branch)');
        incrementComponentMinor('frontend');
    } else {
        console.log('No frontend changes detected, skipping version increment');
    }

    if (backendChanged) {
        console.log('Backend changes detected (compared to main branch)');
        incrementComponentMinor('backend');
    } else {
        console.log('No backend changes detected, skipping version increment');
    }

    if (!frontendChanged && !backendChanged) {
        console.log('No changes detected in frontend or backend');
    }
}

// CLI handling
const component = process.argv[2];
const command = process.argv[3];
const arg = process.argv[4];

if (!component) {
    console.log('Frontend version:', getFrontendVersion());
    console.log('Backend version:', getBackendVersion());
    console.log('Release version:', getReleaseVersion());
} else if (component === 'frontend') {
    if (command === 'get') {
        console.log(getFrontendVersion());
    } else if (command === 'major') {
        setComponentMajor('frontend', arg);
    } else if (command === 'increment-minor') {
        incrementComponentMinor('frontend');
    } else if (command === 'check-changes') {
        console.log(hasGitChanges('frontend/') ? 'changed' : 'unchanged');
    } else {
        console.log('Frontend version:', getFrontendVersion());
    }
} else if (component === 'backend') {
    if (command === 'get') {
        console.log(getBackendVersion());
    } else if (command === 'major') {
        setComponentMajor('backend', arg);
    } else if (command === 'increment-minor') {
        incrementComponentMinor('backend');
    } else if (command === 'check-changes') {
        console.log(hasGitChanges('backend/') ? 'changed' : 'unchanged');
    } else {
        console.log('Backend version:', getBackendVersion());
    }
} else if (component === 'auto') {
    // Automatically increment versions based on git changes
    if (command === 'increment') {
        incrementChangedComponents();
    } else {
        console.log('Usage: node version.js auto increment');
    }
} else if (component === 'release') {
    if (command === 'get') {
        console.log(getReleaseVersion());
    } else {
        console.log('Release version:', getReleaseVersion());
    }
}
