#!/usr/bin/env node
/**
 * Independent Version Management Script
 *
 * Frontend and backend versions are managed independently.
 * Each component tracks its own MAJOR.MINOR version in separate VERSION files.
 * Build numbers are only applied for release tags, not stored in VERSION files.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Version file paths
const frontendVersionPath = path.join(__dirname, '..', 'frontend', 'VERSION');
const backendVersionPath = path.join(__dirname, '..', 'backend', 'VERSION');
const versionTsPath = path.join(__dirname, '..', 'frontend', 'src', 'version.ts');

function hasGitChanges(directory) {
    /**
     * Check if a directory has changes in the current HEAD commit.
     * Works with shallow clones (fetch-depth: 1) in CI.
     *
     * @param {string} directory - Directory path relative to repo root (e.g., 'frontend/', 'backend/')
     * @returns {boolean} True if directory has any changes in HEAD commit, false otherwise
     */
    try {
        // Check if HEAD is a merge commit by counting parents
        const parents = execSync('git show --no-patch --format="%P" HEAD', { encoding: 'utf8' }).trim();
        const isMergeCommit = parents.includes(' '); // Multiple parents means merge commit

        let changedFiles;

        if (isMergeCommit) {
            console.log('Merge commit detected');
            // Compare merge commit with its first parent (target branch before merge)
            changedFiles = execSync(`git diff-tree --no-commit-id --name-only -r HEAD^1 HEAD -- ${directory}/`, { encoding: 'utf8' });
        } else {
            console.log('Regular commit detected');
            // For squash merges or regular commits, compare with previous commit
            changedFiles = execSync(`git diff-tree --no-commit-id --name-only -r HEAD~1 HEAD -- ${directory}/`, { encoding: 'utf8' });
        }

        const files = changedFiles.trim().split('\n').filter(file => file.length > 0);

        if (files.length > 0) {
            console.log('Backend changes detected:');
            files.forEach(file => console.log(file));
            return true;
        } else {
            console.log('No backend changes detected');
            return false;
        }
    } catch (error) {
        console.error('Error checking git changes, incrementing version anyway. Error:', error.message);
        return true;
    }
}

function setVersionInFile(filePath, version) {
    // Ensure directory exists
    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(filePath, version + '\n');
}

function updateFrontendSource(version) {
    // Only update version.ts with MAJOR.MINOR (no build number in source)
    const content = `// Frontend version - auto-generated by version script
export const VERSION = '${version}'
`;
    fs.writeFileSync(versionTsPath, content);
}

function getFrontendVersion() {
    try {
        if (fs.existsSync(versionTsPath)) {
            const content = fs.readFileSync(versionTsPath, 'utf8');
            const match = content.match(/VERSION = '(\d+\.\d+)(?:\.\d+)?'/);
            if (match) {
                return match[1];
            }
        }
        return '0.0';
    } catch {
        return '0.0';
    }
}

function getBackendVersion() {
    try {
        if (fs.existsSync(backendVersionPath)) {
            return fs.readFileSync(backendVersionPath, 'utf8').trim();
        }
        return '0.0';
    } catch {
        return '0.0';
    }
}

function getReleaseVersion() {
    /**
     * Get the full release version combining frontend and backend.
     * Format: {FRONTEND_VERSION}-{BACKEND_VERSION}-{BUILD_NUMBER}
     * Example: 0.3-0.7-42
     */
    const frontendVersion = getFrontendVersion();
    const backendVersion = getBackendVersion();
    const build = process.env.BUILD_NUMBER || 'DEV';
    return `${frontendVersion}-${backendVersion}-${build}`;
}

function incrementMinor(majorMinor) {
    const [major, minor = 0] = majorMinor.split('.').map(Number);
    return `${major}.${minor + 1}`;
}

function setComponentMajor(component, major) {
    const majorMinor = `${major}.0`;

    if (component === 'frontend') {
        updateFrontendSource(majorMinor);
        console.log(`Set frontend version to ${majorMinor}`);
    } else if (component === 'backend') {
        setVersionInFile(backendVersionPath, majorMinor);
        console.log(`Set backend version to ${majorMinor}`);
    }
}

function incrementComponentMinor(component) {
    if (component === 'frontend') {
        const current = getFrontendVersion();
        const next = incrementMinor(current);
        updateFrontendSource(next);
        console.log(`Incremented frontend version to ${next}`);
    } else if (component === 'backend') {
        const current = getBackendVersion();
        const next = incrementMinor(current);
        setVersionInFile(backendVersionPath, next);
        console.log(`Incremented backend version to ${next}`);
    }
}

function incrementChangedComponents() {
    /**
     * Automatically increment versions for components with changes compared to main branch.
     * Only increments if there are changes in the component's directory.
     */
    const frontendChanged = hasGitChanges('frontend/');
    const backendChanged = hasGitChanges('backend/');

    if (frontendChanged) {
        console.log('Frontend changes detected (compared to main branch)');
        incrementComponentMinor('frontend');
    } else {
        console.log('No frontend changes detected, skipping version increment');
    }

    if (backendChanged) {
        console.log('Backend changes detected (compared to main branch)');
        incrementComponentMinor('backend');
    } else {
        console.log('No backend changes detected, skipping version increment');
    }
}

// CLI handling
const component = process.argv[2];
const command = process.argv[3];
const arg = process.argv[4];

if (!component) {
    console.log('Frontend version:', getFrontendVersion());
    console.log('Backend version:', getBackendVersion());
    console.log('Release version:', getReleaseVersion());
} else if (component === 'frontend') {
    if (command === 'get') {
        console.log(getFrontendVersion());
    } else if (command === 'major') {
        setComponentMajor('frontend', arg);
    } else if (command === 'increment-minor') {
        incrementComponentMinor('frontend');
    } else if (command === 'check-changes') {
        console.log(hasGitChanges('frontend/') ? 'changed' : 'unchanged');
    } else {
        console.log('Frontend version:', getFrontendVersion());
    }
} else if (component === 'backend') {
    if (command === 'get') {
        console.log(getBackendVersion());
    } else if (command === 'major') {
        setComponentMajor('backend', arg);
    } else if (command === 'increment-minor') {
        incrementComponentMinor('backend');
    } else if (command === 'check-changes') {
        console.log(hasGitChanges('backend/') ? 'changed' : 'unchanged');
    } else {
        console.log('Backend version:', getBackendVersion());
    }
} else if (component === 'auto') {
    // Automatically increment versions based on git changes
    if (command === 'increment') {
        incrementChangedComponents();
    } else {
        console.log('Usage: node version.js auto increment');
    }
} else if (component === 'release') {
    if (command === 'get') {
        console.log(getReleaseVersion());
    } else {
        console.log('Release version:', getReleaseVersion());
    }
}
